// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUe8RBET80cwiLh6Z8ZMg-LKXZp9yBCdU',
    appId: '1:575477134878:android:09ba6d5078e4f8fcb2a00f',
    messagingSenderId: '575477134878',
    projectId: 'order-track-e8942',
    storageBucket: 'order-track-e8942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKB3t1JUZMK5QKil6ONt-KWCrHy6CLfss',
    appId: '1:575477134878:ios:bbb98330392902fab2a00f',
    messagingSenderId: '575477134878',
    projectId: 'order-track-e8942',
    storageBucket: 'order-track-e8942.appspot.com',
    androidClientId: '575477134878-gstpstluqp1kqlrvb2q5gu5f7g7rtint.apps.googleusercontent.com',
    iosClientId: '575477134878-59ljc50cb9p6mbbagqsfv8q5hemf7bs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackorder',
  );
}
